### ISSUE TITLE
Uncaught ReferenceError: selector is not defined

### ISSUE THREAD

**Issue by albertwoo** [Shmew/Feliz.Recoil#1]
## Description
When I try to use like this:
```fsharp
let test = Recoil.atom("test", promise { return 123})

React.functionComponent (fun () ->
    let v = Recoil.useValue(Tool.test)
    Browser.Dom.console.error v
    Html.text "test"
)
```
I will get error: Uncaught ReferenceError: selector is not defined

**Comment by Shmew** [comment]
Hey @albertwoo I think this is a [bug with Recoil](https://github.com/facebookexperimental/Recoil/issues/142). 

A workaround for now is to use selectors to perform the async operations.

**Comment by Shmew** [comment]
This should now be resolved, let me know if you have any issues with this after updating.

**Comment by albertwoo** [comment]
With the latest version I got this error:
```
File does not exist: xxxx/.fable/Feliz.Recoil.0.7.0/ComputationExpressions/AtomFamily.fs
```

**Comment by Shmew** [comment]
Whoops! I forgot to update the template file, I just pushed the fix.

**Comment by albertwoo** [comment]
Thanks. It works perfect!
