### ISSUE TITLE
Perform a side effect every time a value of a particular atom changes

### ISSUE THREAD

**Issue by joahim** [Shmew/Feliz.Recoil#9]
## Is your feature request related to a problem?
I would like to trigger an action (perform a side effect) every time a value of a particular atom changes but can not find the appropriate hook in the API. Specifically, I would like to update the URL parameters based on the value of the atom.

## Describe the solution you'd like
Ideally, this could be possible by specifying an async callback in the definition of an atom.

## Additional context
Looking at the Recoil spec I could not figure out if this is at all possible with Recoil.

**Comment by Shmew** [comment]
Hi @joahim,

Yes this *will* be possible, but not yet. They're still finalizing the API for what they call `AtomEffects`. It will do exactly this.

The way I've worked around this in my own code are a bit of a pattern that I tend to call observers. What you do is insert a child component into your React tree that will then `Recoil.useValue` to subscribe to the changes in the atom. You would then apply your effects via `React.useEffect`. 

My `Recoil.root` component which is actually a wrapper over recoil's root component does this to add the additional functionality that it has. You can see some examples of how I implement them: [logging](https://github.com/Shmew/Feliz.Recoil/blob/master/src/Feliz.Recoil/Logger.fs), [time travel](https://github.com/Shmew/Feliz.Recoil/blob/master/src/Feliz.Recoil/TimeTravel.fs), and [local/session storage](https://github.com/Shmew/Feliz.Recoil/blob/master/src/Feliz.Recoil/Storage.fs).
